import Head from 'next/head'
import Image from 'next/image'
import BillBoard from '../components/Home/BillBoard'
import Footer from '../components/Home/Footer'
import Header from '../components/Home/Header'
import PlanSection from '../components/Home/PlanSelection'
import Series from '../components/Home/Series'
import SpotLight from '../components/Home/SpotLight'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hulu Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <Header/>
       <Series/>
       <BillBoard/>
       <SpotLight/>
       <PlanSection/>
      </main>

      <footer className={styles.footer}>
        <Footer/>
      </footer>
    </div>
  )
}
